language: node_js
node_js:
  - "8"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $hyperapp-typescript-demo-travis  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
